<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('emrkonservasis', function (Blueprint $table) {
            $table->uuid('id')->primary();

            $table->string('noregister', 25);
            $table->string('noepisode', 25);
            $table->string('nomorrekammedik', 25);
            $table->dateTime('tanggal', 25);
            $table->string('namapasien', 25)->nullable();
            $table->string('pekerjaan', 25)->nullable();
            $table->string('jeniskelamin', 25)->nullable();
            $table->string('alamatpasien', 25)->nullable();
            $table->string('nomortelpon', 25)->nullable();
            $table->string('namaoperator', 25)->nullable();
            $table->string('nim', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_18_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_17_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_16_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_15_55_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_14_54_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_13_53_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_12_52_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_11_51_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_21_61_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_22_62_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_23_63_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_24_64_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_25_65_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_26_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_27_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_28_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_18_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_17_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_16_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_15_55_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_14_54_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_13_53_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_12_52_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_11_51_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_21_61_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_22_62_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_23_63_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_24_64_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_25_65_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_26_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_27_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_28_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_18_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_17_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_16_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_15_55_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_14_54_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_13_53_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_12_52_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_11_51_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_21_61_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_22_62_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_23_63_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_24_64_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_25_65_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_26_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_27_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_28_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_41_81_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_42_82_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_43_83_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_44_84_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_45_85_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_46_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_47_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_48_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_38_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_37_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_36_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_35_75_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_34_74_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_33_73_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_32_72_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_31_71_tv', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_41_81_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_42_82_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_43_83_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_44_84_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_45_85_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_46_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_47_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_48_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_38_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_37_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_36_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_35_75_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_34_74_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_33_73_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_32_72_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_31_71_diagnosis', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_41_81_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_42_82_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_43_83_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_44_84_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_45_85_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_46_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_47_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_48_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_38_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_37_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_36_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_35_75_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_34_74_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_33_73_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_32_72_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanpemeriksaangigi_31_71_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_18_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_17_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_16_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_15_55_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_14_54_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_13_53_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_12_52_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_11_51_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_21_61_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_22_62_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_23_63_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_24_64_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_25_65_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_26_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_27_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_28_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_18_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_17_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_16_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_15_55_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_14_54_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_13_53_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_12_52_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_11_51_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_21_61_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_22_62_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_23_63_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_24_64_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_25_65_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_26_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_27_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_28_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_18_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_17_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_16_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_15_55_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_14_54_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_13_53_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_12_52_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_11_51_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_21_61_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_22_62_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_23_63_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_24_64_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_25_65_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_26_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_27_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_28_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_41_81_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_42_82_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_43_83_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_44_84_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_45_85_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_46_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_47_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_48_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_38_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_37_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_36_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_35_75_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_34_74_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_33_73_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_32_72_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_31_71_tv', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_41_81_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_42_82_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_43_83_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_44_84_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_45_85_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_46_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_47_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_48_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_38_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_37_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_36_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_35_75_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_34_74_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_33_73_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_32_72_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_31_71_diagnosis', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_41_81_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_42_82_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_43_83_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_44_84_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_45_85_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_46_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_47_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_48_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_38_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_37_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_36_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_35_75_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_34_74_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_33_73_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_32_72_rencanaperawatan', 25)->nullable();
            $table->string('ssdhperawatanpemeriksaangigi_31_71_rencanaperawatan', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_sikap', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_status', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_saliva_tanpastimulasi_hidrasi', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_saliva_tanpastimulasi_viskositas', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_saliva_tanpastimulasi_pH', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_saliva_denganstimulasi_hidrasi', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_saliva_denganstimulasi_kecepatanaliranper5menit', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_saliva_denganstimulasi_kapasitasbuffer', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_saliva_denganstimulasi_pH', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_plak_pH', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_plak_aktivitas', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_fluor', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_diet', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_faktormodifikasi_obatpeningkataliransaliva', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_faktormodifikasi_penyakitpenyebabmulutkering', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_faktormodifikasi_protesa', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_faktormodifikasi_kariesaktif', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_faktormodifikasi_sikap', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_faktormodifikasi_keterangan', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_penilaianakhir_saliva', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_penilaianakhir_plak', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_penilaianakhir_diet', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_penilaianakhir_fluor', 25)->nullable();
            $table->string('sblmperawatanfaktorrisikokaries_penilaianakhir_faktormodifikasi', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_sikap', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_status', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_saliva_tanpastimulasi_hidrasi', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_saliva_tanpastimulasi_viskositas', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_saliva_tanpastimulasi_pH', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_saliva_denganstimulasi_hidrasi', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_saliva_denganstimulasi_kecepatanaliranper5menit', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_saliva_denganstimulasi_kapasitasbuffer', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_saliva_denganstimulasi_pH', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_plak_pH', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_plak_aktivitas', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_fluor', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_diet', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_faktormodifikasi_obatpeningkataliransaliva', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_faktormodifikasi_penyakitpenyebabmulutkering', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_faktormodifikasi_protesa', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_faktormodifikasi_kariesaktif', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_faktormodifikasi_sikap', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_faktormodifikasi_keterangan', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_penilaianakhir_saliva', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_penilaianakhir_plak', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_penilaianakhir_diet', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_penilaianakhir_fluor', 25)->nullable();
            $table->string('ssdhperawatanfaktorrisikokaries_penilaianakhir_faktormodifikasi', 25)->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('emrkonservasis');
    }
};
