<?php

namespace App\Repositories;

use App\Models\emrperiodontie;
use App\Models\emrperiodontie_soap;
use App\Models\emrperiodontie_soaps;
use App\Models\hospital;
use App\Models\Year;
use App\Repositories\Interfaces\EmrPeriodontieRepositoryInterface;
use Illuminate\Support\Facades\DB;
use App\Repositories\Interfaces\HospitalRepositoryInterface;
use Carbon\Carbon;

class EmrPeriodontieRepository implements EmrPeriodontieRepositoryInterface
{
    public function createwaktuperawatan($request, $uuid)
    {
        return  DB::table("emrperiodonties")->insert($request);
    }
    // public function createbehaviorrating($data)
    // {
    //     return  DB::table("emrpedodontie_behaviorratings")->insert($data);
    // }
    public function findwaktuperawatan($data)
    {
        return emrperiodontie::where('id', $data->id)->get();
    }
    public function viewemrbyRegOperator($data)
    {
        return emrperiodontie::where('npm', $data->nim)->where('noregister', $data->noregister)->get(); 
    }
    public function updatewaktuperawatan($data)
    {

        $updates = emrperiodontie::where('id', $data->id)->update([
            'nama_mahasiswa' => $data->nama_mahasiswa,
'npm' => $data->npm,
'tahun_klinik' => $data->tahun_klinik,
'opsi_imagemahasiswa' => $data->opsi_imagemahasiswa,
'noregister' => $data->noregister,
'noepisode' => $data->noepisode,
'no_rekammedik' => $data->no_rekammedik,
'kasus_pasien' => $data->kasus_pasien,
'tanggal_pemeriksaan' => $data->tanggal_pemeriksaan,
'pendidikan_pasien' => $data->pendidikan_pasien,
'nama_pasien' => $data->nama_pasien,
'umur_pasien' => $data->umur_pasien,
'jenis_kelamin_pasien' => $data->jenis_kelamin_pasien,
'alamat' => $data->alamat,
'no_telephone_pasien' => $data->no_telephone_pasien,
'pemeriksa' => $data->pemeriksa,
'operator1' => $data->operator1,
'operator2' => $data->operator2,
'operator3' => $data->operator3,
'operator4' => $data->operator4,
'konsuldari' => $data->konsuldari,
'keluhanutama' => $data->keluhanutama,
'anamnesis' => $data->anamnesis,
'gusi_mudah_berdarah' => $data->gusi_mudah_berdarah,
'gusi_mudah_berdarah_lainlain' => $data->gusi_mudah_berdarah_lainlain,
'penyakit_sistemik' => $data->penyakit_sistemik,
'penyakit_sistemik_bilaada' => $data->penyakit_sistemik_bilaada,
'penyakit_sistemik_obat' => $data->penyakit_sistemik_obat,
'diabetes_melitus' => $data->diabetes_melitus,
'diabetes_melituskadargula' => $data->diabetes_melituskadargula,
'merokok' => $data->merokok,
'merokok_perhari' => $data->merokok_perhari,
'merokok_tahun_awal' => $data->merokok_tahun_awal,
'merokok_tahun_akhir' => $data->merokok_tahun_akhir,
'gigi_pernah_tanggal_dalam_keadaan_baik' => $data->gigi_pernah_tanggal_dalam_keadaan_baik,
'keadaan_umum' => $data->keadaan_umum,
'tekanan_darah' => $data->tekanan_darah,
'extra_oral' => $data->extra_oral,
'intra_oral' => $data->intra_oral,
'oral_hygiene_bop' => $data->oral_hygiene_bop,
'oral_hygiene_ci' => $data->oral_hygiene_ci,
'oral_hygiene_pi' => $data->oral_hygiene_pi,
'oral_hygiene_ohis' => $data->oral_hygiene_ohis,
'kesimpulan_ohis' => $data->kesimpulan_ohis,
'rakn_keaadan_gingiva' => $data->rakn_keaadan_gingiva,
'rakn_karang_gigi' => $data->rakn_karang_gigi,
'rakn_oklusi' => $data->rakn_oklusi,
'rakn_artikulasi' => $data->rakn_artikulasi,
'rakn_abrasi_atrisi_abfraksi' => $data->rakn_abrasi_atrisi_abfraksi,
'ram_keaadan_gingiva' => $data->ram_keaadan_gingiva,
'ram_karang_gigi' => $data->ram_karang_gigi,
'ram_oklusi' => $data->ram_oklusi,
'ram_artikulasi' => $data->ram_artikulasi,
'ram_abrasi_atrisi_abfraksi' => $data->ram_abrasi_atrisi_abfraksi,
'rakr_keaadan_gingiva' => $data->rakr_keaadan_gingiva,
'rakr_karang_gigi' => $data->rakr_karang_gigi,
'rakr_oklusi' => $data->rakr_oklusi,
'rakr_artikulasi' => $data->rakr_artikulasi,
'rakr_abrasi_atrisi_abfraksi' => $data->rakr_abrasi_atrisi_abfraksi,
'rbkn_keaadan_gingiva' => $data->rbkn_keaadan_gingiva,
'rbkn_karang_gigi' => $data->rbkn_karang_gigi,
'rbkn_oklusi' => $data->rbkn_oklusi,
'rbkn_artikulasi' => $data->rbkn_artikulasi,
'rbkn_abrasi_atrisi_abfraksi' => $data->rbkn_abrasi_atrisi_abfraksi,
'rbm_keaadan_gingiva' => $data->rbm_keaadan_gingiva,
'rbm_karang_gigi' => $data->rbm_karang_gigi,
'rbm_oklusi' => $data->rbm_oklusi,
'rbm_artikulasi' => $data->rbm_artikulasi,
'rbm_abrasi_atrisi_abfraksi' => $data->rbm_abrasi_atrisi_abfraksi,
'rbkr_keaadan_gingiva' => $data->rbkr_keaadan_gingiva,
'rbkr_karang_gigi' => $data->rbkr_karang_gigi,
'rbkr_oklusi' => $data->rbkr_oklusi,
'rbkr_artikulasi' => $data->rbkr_artikulasi,
'rbkr_abrasi_atrisi_abfraksi' => $data->rbkr_abrasi_atrisi_abfraksi,
'rakn_1_v' => $data->rakn_1_v,
'rakn_1_g' => $data->rakn_1_g,
'rakn_1_pm' => $data->rakn_1_pm,
'rakn_1_pb' => $data->rakn_1_pb,
'rakn_1_pd' => $data->rakn_1_pd,
'rakn_1_pp' => $data->rakn_2_pp,
'rakn_1_o' => $data->rakn_1_o,
'rakn_1_r' => $data->rakn_1_r,
'rakn_1_la' => $data->rakn_1_la,
'rakn_1_mp' => $data->rakn_1_mp,
'rakn_1_bop' => $data->rakn_1_bop,
'rakn_1_tk' => $data->rakn_1_tk,
'rakn_1_fi' => $data->rakn_1_fi,
'rakn_1_k' => $data->rakn_1_k,
'rakn_1_t' => $data->rakn_1_t,
'rakn_2_v' => $data->rakn_2_v,
'rakn_2_g' => $data->rakn_2_g,
'rakn_2_pm' => $data->rakn_2_pm,
'rakn_2_pb' => $data->rakn_2_pb,
'rakn_2_pd' => $data->rakn_2_pd,
'rakn_2_pp' => $data->rakn_2_pp,
'rakn_2_o' => $data->rakn_2_o,
'rakn_2_r' => $data->rakn_2_r,
'rakn_2_la' => $data->rakn_2_la,
'rakn_2_mp' => $data->rakn_2_mp,
'rakn_2_bop' => $data->rakn_2_bop,
'rakn_2_tk' => $data->rakn_2_tk,
'rakn_2_fi' => $data->rakn_2_fi,
'rakn_2_k' => $data->rakn_2_k,
'rakn_2_t' => $data->rakn_2_t,
'rakn_3_v' => $data->rakn_3_v,
'rakn_3_g' => $data->rakn_3_g,
'rakn_3_pm' => $data->rakn_3_pm,
'rakn_3_pb' => $data->rakn_3_pb,
'rakn_3_pd' => $data->rakn_3_pd,
'rakn_3_pp' => $data->rakn_3_pp,
'rakn_3_o' => $data->rakn_3_o,
'rakn_3_r' => $data->rakn_3_r,
'rakn_3_la' => $data->rakn_3_la,
'rakn_3_mp' => $data->rakn_3_mp,
'rakn_3_bop' => $data->rakn_3_bop,
'rakn_3_tk' => $data->rakn_3_tk,
'rakn_3_fi' => $data->rakn_3_fi,
'rakn_3_k' => $data->rakn_3_k,
'rakn_3_t' => $data->rakn_3_t,
'rakn_4_v' => $data->rakn_4_v,
'rakn_4_g' => $data->rakn_4_g,
'rakn_4_pm' => $data->rakn_4_pm,
'rakn_4_pb' => $data->rakn_4_pb,
'rakn_4_pd' => $data->rakn_4_pd,
'rakn_4_pp' => $data->rakn_4_pp,
'rakn_4_o' => $data->rakn_4_o,
'rakn_4_r' => $data->rakn_4_r,
'rakn_4_la' => $data->rakn_4_la,
'rakn_4_mp' => $data->rakn_4_mp,
'rakn_4_bop' => $data->rakn_4_bop,
'rakn_4_tk' => $data->rakn_4_tk,
'rakn_4_fi' => $data->rakn_4_fi,
'rakn_4_k' => $data->rakn_4_k,
'rakn_4_t' => $data->rakn_4_t,
'rakn_5_v' => $data->rakn_5_v,
'rakn_5_g' => $data->rakn_5_g,
'rakn_5_pm' => $data->rakn_5_pm,
'rakn_5_pb' => $data->rakn_5_pb,
'rakn_5_pd' => $data->rakn_5_pd,
'rakn_5_pp' => $data->rakn_5_pp,
'rakn_5_o' => $data->rakn_5_o,
'rakn_5_r' => $data->rakn_5_r,
'rakn_5_la' => $data->rakn_5_la,
'rakn_5_mp' => $data->rakn_5_mp,
'rakn_5_bop' => $data->rakn_5_bop,
'rakn_5_tk' => $data->rakn_5_tk,
'rakn_5_fi' => $data->rakn_5_fi,
'rakn_5_k' => $data->rakn_5_k,
'rakn_5_t' => $data->rakn_5_t,
'rakn_6_v' => $data->rakn_6_v,
'rakn_6_g' => $data->rakn_6_g,
'rakn_6_pm' => $data->rakn_6_pm,
'rakn_6_pb' => $data->rakn_6_pb,
'rakn_6_pd' => $data->rakn_6_pd,
'rakn_6_pp' => $data->rakn_6_pp,
'rakn_6_o' => $data->rakn_6_o,
'rakn_6_r' => $data->rakn_6_r,
'rakn_6_la' => $data->rakn_6_la,
'rakn_6_mp' => $data->rakn_6_mp,
'rakn_6_bop' => $data->rakn_6_bop,
'rakn_6_tk' => $data->rakn_6_tk,
'rakn_6_fi' => $data->rakn_6_fi,
'rakn_6_k' => $data->rakn_6_k,
'rakn_6_t' => $data->rakn_6_t,
'rakn_7_v' => $data->rakn_7_v,
'rakn_7_g' => $data->rakn_7_g,
'rakn_7_pm' => $data->rakn_7_pm,
'rakn_7_pb' => $data->rakn_7_pb,
'rakn_7_pd' => $data->rakn_7_pd,
'rakn_7_pp' => $data->rakn_7_pp,
'rakn_7_o' => $data->rakn_7_o,
'rakn_7_r' => $data->rakn_7_r,
'rakn_7_la' => $data->rakn_7_la,
'rakn_7_mp' => $data->rakn_7_mp,
'rakn_7_bop' => $data->rakn_7_bop,
'rakn_7_tk' => $data->rakn_7_tk,
'rakn_7_fi' => $data->rakn_7_fi,
'rakn_7_k' => $data->rakn_7_k,
'rakn_7_t' => $data->rakn_7_t,
'rakn_8_v' => $data->rakn_8_v,
'rakn_8_g' => $data->rakn_8_g,
'rakn_8_pm' => $data->rakn_8_pm,
'rakn_8_pb' => $data->rakn_8_pb,
'rakn_8_pd' => $data->rakn_8_pd,
'rakn_8_pp' => $data->rakn_8_pp,
'rakn_8_o' => $data->rakn_8_o,
'rakn_8_r' => $data->rakn_8_r,
'rakn_8_la' => $data->rakn_8_la,
'rakn_8_mp' => $data->rakn_8_mp,
'rakn_8_bop' => $data->rakn_8_bop,
'rakn_8_tk' => $data->rakn_8_tk,
'rakn_8_fi' => $data->rakn_8_fi,
'rakn_8_k' => $data->rakn_8_k,
'rakn_8_t' => $data->rakn_8_t,
'rakr_1_v' => $data->rakr_1_v,
'rakr_1_g' => $data->rakr_1_g,
'rakr_1_pm' => $data->rakr_1_pm,
'rakr_1_pb' => $data->rakr_1_pb,
'rakr_1_pd' => $data->rakr_1_pd,
'rakr_1_pp' => $data->rakr_1_pp,
'rakr_1_o' => $data->rakr_1_o,
'rakr_1_r' => $data->rakr_1_r,
'rakr_1_la' => $data->rakr_1_la,
'rakr_1_mp' => $data->rakr_1_mp,
'rakr_1_bop' => $data->rakr_1_bop,
'rakr_1_tk' => $data->rakr_1_tk,
'rakr_1_fi' => $data->rakr_1_fi,
'rakr_1_k' => $data->rakr_1_k,
'rakr_1_t' => $data->rakr_1_t,
'rakr_2_v' => $data->rakr_2_v,
'rakr_2_g' => $data->rakr_2_g,
'rakr_2_pm' => $data->rakr_2_pm,
'rakr_2_pb' => $data->rakr_2_pb,
'rakr_2_pd' => $data->rakr_2_pd,
'rakr_2_pp' => $data->rakr_2_pp,
'rakr_2_o' => $data->rakr_2_o,
'rakr_2_r' => $data->rakr_2_r,
'rakr_2_la' => $data->rakr_2_la,
'rakr_2_mp' => $data->rakr_2_mp,
'rakr_2_bop' => $data->rakr_2_bop,
'rakr_2_tk' => $data->rakr_2_tk,
'rakr_2_fi' => $data->rakr_2_fi,
'rakr_2_k' => $data->rakr_2_k,
'rakr_2_t' => $data->rakr_2_t,
'rakr_3_v' => $data->rakr_3_v,
'rakr_3_g' => $data->rakr_3_g,
'rakr_3_pm' => $data->rakr_3_pm,
'rakr_3_pb' => $data->rakr_3_pb,
'rakr_3_pd' => $data->rakr_3_pd,
'rakr_3_pp' => $data->rakr_3_pp,
'rakr_3_o' => $data->rakr_3_o,
'rakr_3_r' => $data->rakr_3_r,
'rakr_3_la' => $data->rakr_3_la,
'rakr_3_mp' => $data->rakr_3_mp,
'rakr_3_bop' => $data->rakr_3_bop,
'rakr_3_tk' => $data->rakr_3_tk,
'rakr_3_fi' => $data->rakr_3_fi,
'rakr_3_k' => $data->rakr_3_k,
'rakr_3_t' => $data->rakr_3_t,
'rakr_4_v' => $data->rakr_4_v,
'rakr_4_g' => $data->rakr_4_g,
'rakr_4_pm' => $data->rakr_4_pm,
'rakr_4_pb' => $data->rakr_4_pb,
'rakr_4_pd' => $data->rakr_4_pd,
'rakr_4_pp' => $data->rakr_4_pp,
'rakr_4_o' => $data->rakr_4_o,
'rakr_4_r' => $data->rakr_4_r,
'rakr_4_la' => $data->rakr_4_la,
'rakr_4_mp' => $data->rakr_4_mp,
'rakr_4_bop' => $data->rakr_4_bop,
'rakr_4_tk' => $data->rakr_4_tk,
'rakr_4_fi' => $data->rakr_4_fi,
'rakr_4_k' => $data->rakr_4_k,
'rakr_4_t' => $data->rakr_4_t,
'rakr_5_v' => $data->rakr_5_v,
'rakr_5_g' => $data->rakr_5_g,
'rakr_5_pm' => $data->rakr_5_pm,
'rakr_5_pb' => $data->rakr_5_pb,
'rakr_5_pd' => $data->rakr_5_pd,
'rakr_5_pp' => $data->rakr_5_pp,
'rakr_5_o' => $data->rakr_5_o,
'rakr_5_r' => $data->rakr_5_r,
'rakr_5_la' => $data->rakr_5_la,
'rakr_5_mp' => $data->rakr_5_mp,
'rakr_5_bop' => $data->rakr_5_bop,
'rakr_5_tk' => $data->rakr_5_tk,
'rakr_5_fi' => $data->rakr_5_fi,
'rakr_5_k' => $data->rakr_5_k,
'rakr_5_t' => $data->rakr_5_t,
'rakr_6_v' => $data->rakr_6_v,
'rakr_6_g' => $data->rakr_6_g,
'rakr_6_pm' => $data->rakr_6_pm,
'rakr_6_pb' => $data->rakr_6_pb,
'rakr_6_pd' => $data->rakr_6_pd,
'rakr_6_pp' => $data->rakr_6_pp,
'rakr_6_o' => $data->rakr_6_o,
'rakr_6_r' => $data->rakr_6_r,
'rakr_6_la' => $data->rakr_6_la,
'rakr_6_mp' => $data->rakr_6_mp,
'rakr_6_bop' => $data->rakr_6_bop,
'rakr_6_tk' => $data->rakr_6_tk,
'rakr_6_fi' => $data->rakr_6_fi,
'rakr_6_k' => $data->rakr_6_k,
'rakr_6_t' => $data->rakr_6_t,
'rakr_7_v' => $data->rakr_7_v,
'rakr_7_g' => $data->rakr_7_g,
'rakr_7_pm' => $data->rakr_7_pm,
'rakr_7_pb' => $data->rakr_7_pb,
'rakr_7_pd' => $data->rakr_7_pd,
'rakr_7_pp' => $data->rakr_7_pp,
'rakr_7_o' => $data->rakr_7_o,
'rakr_7_r' => $data->rakr_7_r,
'rakr_7_la' => $data->rakr_7_la,
'rakr_7_mp' => $data->rakr_7_mp,
'rakr_7_bop' => $data->rakr_7_bop,
'rakr_7_tk' => $data->rakr_7_tk,
'rakr_7_fi' => $data->rakr_7_fi,
'rakr_7_k' => $data->rakr_7_k,
'rakr_7_t' => $data->rakr_7_t,
'rakr_8_v' => $data->rakr_8_v,
'rakr_8_g' => $data->rakr_8_g,
'rakr_8_pm' => $data->rakr_8_pm,
'rakr_8_pb' => $data->rakr_8_pb,
'rakr_8_pd' => $data->rakr_8_pd,
'rakr_8_pp' => $data->rakr_8_pp,
'rakr_8_o' => $data->rakr_8_o,
'rakr_8_r' => $data->rakr_8_r,
'rakr_8_la' => $data->rakr_8_la,
'rakr_8_mp' => $data->rakr_8_mp,
'rakr_8_bop' => $data->rakr_8_bop,
'rakr_8_tk' => $data->rakr_8_tk,
'rakr_8_fi' => $data->rakr_8_fi,
'rakr_8_k' => $data->rakr_8_k,
'rakr_8_t' => $data->rakr_8_t,
'rbkn_1_v' => $data->rbkn_1_v,
'rbkn_1_g' => $data->rbkn_1_g,
'rbkn_1_pm' => $data->rbkn_1_pm,
'rbkn_1_pb' => $data->rbkn_1_pb,
'rbkn_1_pd' => $data->rbkn_1_pd,
'rbkn_1_pp' => $data->rbkn_1_pp,
'rbkn_1_o' => $data->rbkn_1_o,
'rbkn_1_r' => $data->rbkn_1_r,
'rbkn_1_la' => $data->rbkn_1_la,
'rbkn_1_mp' => $data->rbkn_1_mp,
'rbkn_1_bop' => $data->rbkn_1_bop,
'rbkn_1_tk' => $data->rbkn_1_tk,
'rbkn_1_fi' => $data->rbkn_1_fi,
'rbkn_1_k' => $data->rbkn_1_k,
'rbkn_1_t' => $data->rbkn_1_t,
'rbkn_2_v' => $data->rbkn_2_v,
'rbkn_2_g' => $data->rbkn_2_g,
'rbkn_2_pm' => $data->rbkn_2_pm,
'rbkn_2_pb' => $data->rbkn_2_pb,
'rbkn_2_pd' => $data->rbkn_2_pd,
'rbkn_2_pp' => $data->rbkn_2_pp,
'rbkn_2_o' => $data->rbkn_2_o,
'rbkn_2_r' => $data->rbkn_2_r,
'rbkn_2_la' => $data->rbkn_2_la,
'rbkn_2_mp' => $data->rbkn_2_mp,
'rbkn_2_bop' => $data->rbkn_2_bop,
'rbkn_2_tk' => $data->rbkn_2_tk,
'rbkn_2_fi' => $data->rbkn_2_fi,
'rbkn_2_k' => $data->rbkn_2_k,
'rbkn_2_t' => $data->rbkn_2_t,
'rbkn_3_v' => $data->rbkn_3_v,
'rbkn_3_g' => $data->rbkn_3_g,
'rbkn_3_pm' => $data->rbkn_3_pm,
'rbkn_3_pb' => $data->rbkn_3_pb,
'rbkn_3_pd' => $data->rbkn_3_pd,
'rbkn_3_pp' => $data->rbkn_3_pp,
'rbkn_3_o' => $data->rbkn_3_o,
'rbkn_3_r' => $data->rbkn_3_r,
'rbkn_3_la' => $data->rbkn_3_la,
'rbkn_3_mp' => $data->rbkn_3_mp,
'rbkn_3_bop' => $data->rbkn_3_bop,
'rbkn_3_tk' => $data->rbkn_3_tk,
'rbkn_3_fi' => $data->rbkn_3_fi,
'rbkn_3_k' => $data->rbkn_3_k,
'rbkn_3_t' => $data->rbkn_3_t,
'rbkn_4_v' => $data->rbkn_4_v,
'rbkn_4_g' => $data->rbkn_4_g,
'rbkn_4_pm' => $data->rbkn_4_pm,
'rbkn_4_pb' => $data->rbkn_4_pb,
'rbkn_4_pd' => $data->rbkn_4_pd,
'rbkn_4_pp' => $data->rbkn_4_pp,
'rbkn_4_o' => $data->rbkn_4_o,
'rbkn_4_r' => $data->rbkn_4_r,
'rbkn_4_la' => $data->rbkn_4_la,
'rbkn_4_mp' => $data->rbkn_4_mp,
'rbkn_4_bop' => $data->rbkn_4_bop,
'rbkn_4_tk' => $data->rbkn_4_tk,
'rbkn_4_fi' => $data->rbkn_4_fi,
'rbkn_4_k' => $data->rbkn_4_k,
'rbkn_4_t' => $data->rbkn_4_t,
'rbkn_5_v' => $data->rbkn_5_v,
'rbkn_5_g' => $data->rbkn_5_g,
'rbkn_5_pm' => $data->rbkn_5_pm,
'rbkn_5_pb' => $data->rbkn_5_pb,
'rbkn_5_pd' => $data->rbkn_5_pd,
'rbkn_5_pp' => $data->rbkn_5_pp,
'rbkn_5_o' => $data->rbkn_5_o,
'rbkn_5_r' => $data->rbkn_5_r,
'rbkn_5_la' => $data->rbkn_5_la,
'rbkn_5_mp' => $data->rbkn_5_mp,
'rbkn_5_bop' => $data->rbkn_5_bop,
'rbkn_5_tk' => $data->rbkn_5_tk,
'rbkn_5_fi' => $data->rbkn_5_fi,
'rbkn_5_k' => $data->rbkn_5_k,
'rbkn_5_t' => $data->rbkn_5_t,
'rbkn_6_v' => $data->rbkn_6_v,
'rbkn_6_g' => $data->rbkn_6_g,
'rbkn_6_pm' => $data->rbkn_6_pm,
'rbkn_6_pb' => $data->rbkn_6_pb,
'rbkn_6_pd' => $data->rbkn_6_pd,
'rbkn_6_pp' => $data->rbkn_6_pp,
'rbkn_6_o' => $data->rbkn_6_o,
'rbkn_6_r' => $data->rbkn_6_r,
'rbkn_6_la' => $data->rbkn_6_la,
'rbkn_6_mp' => $data->rbkn_6_mp,
'rbkn_6_bop' => $data->rbkn_6_bop,
'rbkn_6_tk' => $data->rbkn_6_tk,
'rbkn_6_fi' => $data->rbkn_6_fi,
'rbkn_6_k' => $data->rbkn_6_k,
'rbkn_6_t' => $data->rbkn_6_t,
'rbkn_7_v' => $data->rbkn_7_v,
'rbkn_7_g' => $data->rbkn_7_g,
'rbkn_7_pm' => $data->rbkn_7_pm,
'rbkn_7_pb' => $data->rbkn_7_pb,
'rbkn_7_pd' => $data->rbkn_7_pd,
'rbkn_7_pp' => $data->rbkn_7_pp,
'rbkn_7_o' => $data->rbkn_7_o,
'rbkn_7_r' => $data->rbkn_7_r,
'rbkn_7_la' => $data->rbkn_7_la,
'rbkn_7_mp' => $data->rbkn_7_mp,
'rbkn_7_bop' => $data->rbkn_7_bop,
'rbkn_7_tk' => $data->rbkn_7_tk,
'rbkn_7_fi' => $data->rbkn_7_fi,
'rbkn_7_k' => $data->rbkn_7_k,
'rbkn_7_t' => $data->rbkn_7_t,
'rbkn_8_v' => $data->rbkn_8_v,
'rbkn_8_g' => $data->rbkn_8_g,
'rbkn_8_pm' => $data->rbkn_8_pm,
'rbkn_8_pb' => $data->rbkn_8_pb,
'rbkn_8_pd' => $data->rbkn_8_pd,
'rbkn_8_pp' => $data->rbkn_8_pp,
'rbkn_8_o' => $data->rbkn_8_o,
'rbkn_8_r' => $data->rbkn_8_r,
'rbkn_8_la' => $data->rbkn_8_la,
'rbkn_8_mp' => $data->rbkn_8_mp,
'rbkn_8_bop' => $data->rbkn_8_bop,
'rbkn_8_tk' => $data->rbkn_8_tk,
'rbkn_8_fi' => $data->rbkn_8_fi,
'rbkn_8_k' => $data->rbkn_8_k,
'rbkn_8_t' => $data->rbkn_8_t,
'rbkr_1_v' => $data->rbkr_1_v,
'rbkr_1_g' => $data->rbkr_1_g,
'rbkr_1_pm' => $data->rbkr_1_pm,
'rbkr_1_pb' => $data->rbkr_1_pb,
'rbkr_1_pd' => $data->rbkr_1_pd,
'rbkr_1_pp' => $data->rbkr_1_pp,
'rbkr_1_o' => $data->rbkr_1_o,
'rbkr_1_r' => $data->rbkr_1_r,
'rbkr_1_la' => $data->rbkr_1_la,
'rbkr_1_mp' => $data->rbkr_1_mp,
'rbkr_1_bop' => $data->rbkr_1_bop,
'rbkr_1_tk' => $data->rbkr_1_tk,
'rbkr_1_fi' => $data->rbkr_1_fi,
'rbkr_1_k' => $data->rbkr_1_k,
'rbkr_1_t' => $data->rbkr_1_t,
'rbkr_2_v' => $data->rbkr_2_v,
'rbkr_2_g' => $data->rbkr_2_g,
'rbkr_2_pm' => $data->rbkr_2_pm,
'rbkr_2_pb' => $data->rbkr_2_pb,
'rbkr_2_pd' => $data->rbkr_2_pd,
'rbkr_2_pp' => $data->rbkr_2_pp,
'rbkr_2_o' => $data->rbkr_2_o,
'rbkr_2_r' => $data->rbkr_2_r,
'rbkr_2_la' => $data->rbkr_2_la,
'rbkr_2_mp' => $data->rbkr_2_mp,
'rbkr_2_bop' => $data->rbkr_2_bop,
'rbkr_2_tk' => $data->rbkr_2_tk,
'rbkr_2_fi' => $data->rbkr_2_fi,
'rbkr_2_k' => $data->rbkr_2_k,
'rbkr_2_t' => $data->rbkr_2_t,
'rbkr_3_v' => $data->rbkr_3_v,
'rbkr_3_g' => $data->rbkr_3_g,
'rbkr_3_pm' => $data->rbkr_3_pm,
'rbkr_3_pb' => $data->rbkr_3_pb,
'rbkr_3_pd' => $data->rbkr_3_pd,
'rbkr_3_pp' => $data->rbkr_3_pp,
'rbkr_3_o' => $data->rbkr_3_o,
'rbkr_3_r' => $data->rbkr_3_r,
'rbkr_3_la' => $data->rbkr_3_la,
'rbkr_3_mp' => $data->rbkr_3_mp,
'rbkr_3_bop' => $data->rbkr_3_bop,
'rbkr_3_tk' => $data->rbkr_3_tk,
'rbkr_3_fi' => $data->rbkr_3_fi,
'rbkr_3_k' => $data->rbkr_3_k,
'rbkr_3_t' => $data->rbkr_3_t,
'rbkr_4_v' => $data->rbkr_4_v,
'rbkr_4_g' => $data->rbkr_4_g,
'rbkr_4_pm' => $data->rbkr_4_pm,
'rbkr_4_pb' => $data->rbkr_4_pb,
'rbkr_4_pd' => $data->rbkr_4_pd,
'rbkr_4_pp' => $data->rbkr_4_pp,
'rbkr_4_o' => $data->rbkr_4_o,
'rbkr_4_r' => $data->rbkr_4_r,
'rbkr_4_la' => $data->rbkr_4_la,
'rbkr_4_mp' => $data->rbkr_4_mp,
'rbkr_4_bop' => $data->rbkr_4_bop,
'rbkr_4_tk' => $data->rbkr_4_tk,
'rbkr_4_fi' => $data->rbkr_4_fi,
'rbkr_4_k' => $data->rbkr_4_k,
'rbkr_4_t' => $data->rbkr_4_t,
'rbkr_5_v' => $data->rbkr_5_v,
'rbkr_5_g' => $data->rbkr_5_g,
'rbkr_5_pm' => $data->rbkr_5_pm,
'rbkr_5_pb' => $data->rbkr_5_pb,
'rbkr_5_pd' => $data->rbkr_5_pd,
'rbkr_5_pp' => $data->rbkr_5_pp,
'rbkr_5_o' => $data->rbkr_5_o,
'rbkr_5_r' => $data->rbkr_5_r,
'rbkr_5_la' => $data->rbkr_5_la,
'rbkr_5_mp' => $data->rbkr_5_mp,
'rbkr_5_bop' => $data->rbkr_5_bop,
'rbkr_5_tk' => $data->rbkr_5_tk,
'rbkr_5_fi' => $data->rbkr_5_fi,
'rbkr_5_k' => $data->rbkr_5_k,
'rbkr_5_t' => $data->rbkr_5_t,
'rbkr_6_v' => $data->rbkr_6_v,
'rbkr_6_g' => $data->rbkr_6_g,
'rbkr_6_pm' => $data->rbkr_6_pm,
'rbkr_6_pb' => $data->rbkr_6_pb,
'rbkr_6_pd' => $data->rbkr_6_pd,
'rbkr_6_pp' => $data->rbkr_6_pp,
'rbkr_6_o' => $data->rbkr_6_o,
'rbkr_6_r' => $data->rbkr_6_r,
'rbkr_6_la' => $data->rbkr_6_la,
'rbkr_6_mp' => $data->rbkr_6_mp,
'rbkr_6_bop' => $data->rbkr_6_bop,
'rbkr_6_tk' => $data->rbkr_6_tk,
'rbkr_6_fi' => $data->rbkr_6_fi,
'rbkr_6_k' => $data->rbkr_6_k,
'rbkr_6_t' => $data->rbkr_6_t,
'rbkr_7_v' => $data->rbkr_7_v,
'rbkr_7_g' => $data->rbkr_7_g,
'rbkr_7_pm' => $data->rbkr_7_pm,
'rbkr_7_pb' => $data->rbkr_7_pb,
'rbkr_7_pd' => $data->rbkr_7_pd,
'rbkr_7_pp' => $data->rbkr_7_pp,
'rbkr_7_o' => $data->rbkr_7_o,
'rbkr_7_r' => $data->rbkr_7_r,
'rbkr_7_la' => $data->rbkr_7_la,
'rbkr_7_mp' => $data->rbkr_7_mp,
'rbkr_7_bop' => $data->rbkr_7_bop,
'rbkr_7_tk' => $data->rbkr_7_tk,
'rbkr_7_fi' => $data->rbkr_7_fi,
'rbkr_7_k' => $data->rbkr_7_k,
'rbkr_7_t' => $data->rbkr_7_t,
'rbkr_8_v' => $data->rbkr_8_v,
'rbkr_8_g' => $data->rbkr_8_g,
'rbkr_8_pm' => $data->rbkr_8_pm,
'rbkr_8_pb' => $data->rbkr_8_pb,
'rbkr_8_pd' => $data->rbkr_8_pd,
'rbkr_8_pp' => $data->rbkr_8_pp,
'rbkr_8_o' => $data->rbkr_8_o,
'rbkr_8_r' => $data->rbkr_8_r,
'rbkr_8_la' => $data->rbkr_8_la,
'rbkr_8_mp' => $data->rbkr_8_mp,
'rbkr_8_bop' => $data->rbkr_8_bop,
'rbkr_8_tk' => $data->rbkr_8_tk,
'rbkr_8_fi' => $data->rbkr_8_fi,
'rbkr_8_k' => $data->rbkr_8_k,
'rbkr_8_t' => $data->rbkr_8_t,
'diagnosis_klinik' => $data->diagnosis_klinik,
'gambaran_radiografis' => $data->gambaran_radiografis,
'indikasi' => $data->indikasi,
'terapi' => $data->terapi,
'keterangan' => $data->keterangan,
'prognosis_umum' => $data->prognosis_umum,
'prognosis_lokal' => $data->prognosis_lokal,
'p1_tanggal' => $data->p1_tanggal,
'p1_indeksplak_ra_el16_b' => $data->p1_indeksplak_ra_el16_b,
'p1_indeksplak_ra_el12_b' => $data->p1_indeksplak_ra_el12_b,
'p1_indeksplak_ra_el11_b' => $data->p1_indeksplak_ra_el11_b,
'p1_indeksplak_ra_el21_b' => $data->p1_indeksplak_ra_el21_b,
'p1_indeksplak_ra_el22_b' => $data->p1_indeksplak_ra_el22_b,
'p1_indeksplak_ra_el24_b' => $data->p1_indeksplak_ra_el24_b,
'p1_indeksplak_ra_el26_b' => $data->p1_indeksplak_ra_el26_b,
'p1_indeksplak_ra_el16_l' => $data->p1_indeksplak_ra_el16_l,
'p1_indeksplak_ra_el12_l' => $data->p1_indeksplak_ra_el12_l,
'p1_indeksplak_ra_el11_l' => $data->p1_indeksplak_ra_el11_l,
'p1_indeksplak_ra_el21_l' => $data->p1_indeksplak_ra_el21_l,
'p1_indeksplak_ra_el22_l' => $data->p1_indeksplak_ra_el22_l,
'p1_indeksplak_ra_el24_l' => $data->p1_indeksplak_ra_el24_l,
'p1_indeksplak_ra_el26_l' => $data->p1_indeksplak_ra_el26_l,
'p1_indeksplak_rb_el36_b' => $data->p1_indeksplak_rb_el36_b,
'p1_indeksplak_rb_el34_b' => $data->p1_indeksplak_rb_el34_b,
'p1_indeksplak_rb_el32_b' => $data->p1_indeksplak_rb_el32_b,
'p1_indeksplak_rb_el31_b' => $data->p1_indeksplak_rb_el31_b,
'p1_indeksplak_rb_el41_b' => $data->p1_indeksplak_rb_el41_b,
'p1_indeksplak_rb_el42_b' => $data->p1_indeksplak_rb_el42_b,
'p1_indeksplak_rb_el46_b' => $data->p1_indeksplak_rb_el46_b,
'p1_indeksplak_rb_el36_l' => $data->p1_indeksplak_rb_el36_l,
'p1_indeksplak_rb_el34_l' => $data->p1_indeksplak_rb_el34_l,
'p1_indeksplak_rb_el32_l' => $data->p1_indeksplak_rb_el32_l,
'p1_indeksplak_rb_el31_l' => $data->p1_indeksplak_rb_el31_l,
'p1_indeksplak_rb_el41_l' => $data->p1_indeksplak_rb_el41_l,
'p1_indeksplak_rb_el42_l' => $data->p1_indeksplak_rb_el42_l,
'p1_indeksplak_rb_el46_l' => $data->p1_indeksplak_rb_el46_l,
'p1_bop_ra_el16_b' => $data->p1_bop_ra_el16_b,
'p1_bop_ra_el12_b' => $data->p1_bop_ra_el12_b,
'p1_bop_ra_el11_b' => $data->p1_bop_ra_el11_b,
'p1_bop_ra_el21_b' => $data->p1_bop_ra_el21_b,
'p1_bop_ra_el22_b' => $data->p1_bop_ra_el22_b,
'p1_bop_ra_el24_b' => $data->p1_bop_ra_el24_b,
'p1_bop_ra_el26_b' => $data->p1_bop_ra_el26_b,
'p1_bop_ra_el16_l' => $data->p1_bop_ra_el16_l,
'p1_bop_ra_el12_l' => $data->p1_bop_ra_el12_l,
'p1_bop_ra_el11_l' => $data->p1_bop_ra_el11_l,
'p1_bop_ra_el21_l' => $data->p1_bop_ra_el21_l,
'p1_bop_ra_el22_l' => $data->p1_bop_ra_el22_l,
'p1_bop_ra_el24_l' => $data->p1_bop_ra_el24_l,
'p1_bop_ra_el26_l' => $data->p1_bop_ra_el26_l,
'p1_bop_rb_el36_b' => $data->p1_bop_rb_el36_b,
'p1_bop_rb_el34_b' => $data->p1_bop_rb_el34_b,
'p1_bop_rb_el32_b' => $data->p1_bop_rb_el32_b,
'p1_bop_rb_el31_b' => $data->p1_bop_rb_el31_b,
'p1_bop_rb_el41_b' => $data->p1_bop_rb_el41_b,
'p1_bop_rb_el42_b' => $data->p1_bop_rb_el42_b,
'p1_bop_rb_el46_b' => $data->p1_bop_rb_el46_b,
'p1_bop_rb_el36_l' => $data->p1_bop_rb_el36_l,
'p1_bop_rb_el34_l' => $data->p1_bop_rb_el34_l,
'p1_bop_rb_el32_l' => $data->p1_bop_rb_el32_l,
'p1_bop_rb_el31_l' => $data->p1_bop_rb_el31_l,
'p1_bop_rb_el41_l' => $data->p1_bop_rb_el41_l,
'p1_bop_rb_el42_l' => $data->p1_bop_rb_el42_l,
'p1_bop_rb_el46_l' => $data->p1_bop_rb_el46_l,
'p1_indekskalkulus_ra_el16_b' => $data->p1_indekskalkulus_ra_el16_b,
'p1_indekskalkulus_ra_el26_b' => $data->p1_indekskalkulus_ra_el26_b,
'p1_indekskalkulus_ra_el16_l' => $data->p1_indekskalkulus_ra_el16_l,
'p1_indekskalkulus_ra_el26_l' => $data->p1_indekskalkulus_ra_el26_l,
'p1_indekskalkulus_rb_el36_b' => $data->p1_indekskalkulus_rb_el36_b,
'p1_indekskalkulus_rb_el34_b' => $data->p1_indekskalkulus_rb_el34_b,
'p1_indekskalkulus_rb_el32_b' => $data->p1_indekskalkulus_rb_el32_b,
'p1_indekskalkulus_rb_el31_b' => $data->p1_indekskalkulus_rb_el31_b,
'p1_indekskalkulus_rb_el41_b' => $data->p1_indekskalkulus_rb_el41_b,
'p1_indekskalkulus_rb_el42_b' => $data->p1_indekskalkulus_rb_el42_b,
'p1_indekskalkulus_rb_el46_b' => $data->p1_indekskalkulus_rb_el46_b,
'p1_indekskalkulus_rb_el36_l' => $data->p1_indekskalkulus_rb_el36_l,
'p1_indekskalkulus_rb_el34_l' => $data->p1_indekskalkulus_rb_el34_l,
'p1_indekskalkulus_rb_el32_l' => $data->p1_indekskalkulus_rb_el32_l,
'p1_indekskalkulus_rb_el31_l' => $data->p1_indekskalkulus_rb_el31_l,
'p1_indekskalkulus_rb_el41_l' => $data->p1_indekskalkulus_rb_el41_l,
'p1_indekskalkulus_rb_el42_l' => $data->p1_indekskalkulus_rb_el42_l,
'p1_indekskalkulus_rb_el46_l' => $data->p1_indekskalkulus_rb_el46_l,
'p2_tanggal' => $data->p2_tanggal,
'p2_indeksplak_ra_el16_b' => $data->p2_indeksplak_ra_el16_b,
'p2_indeksplak_ra_el12_b' => $data->p2_indeksplak_ra_el12_b,
'p2_indeksplak_ra_el11_b' => $data->p2_indeksplak_ra_el11_b,
'p2_indeksplak_ra_el21_b' => $data->p2_indeksplak_ra_el21_b,
'p2_indeksplak_ra_el22_b' => $data->p2_indeksplak_ra_el22_b,
'p2_indeksplak_ra_el24_b' => $data->p2_indeksplak_ra_el24_b,
'p2_indeksplak_ra_el26_b' => $data->p2_indeksplak_ra_el26_b,
'p2_indeksplak_ra_el16_l' => $data->p2_indeksplak_ra_el16_l,
'p2_indeksplak_ra_el12_l' => $data->p2_indeksplak_ra_el12_l,
'p2_indeksplak_ra_el11_l' => $data->p2_indeksplak_ra_el11_l,
'p2_indeksplak_ra_el21_l' => $data->p2_indeksplak_ra_el21_l,
'p2_indeksplak_ra_el22_l' => $data->p2_indeksplak_ra_el22_l,
'p2_indeksplak_ra_el24_l' => $data->p2_indeksplak_ra_el24_l,
'p2_indeksplak_ra_el26_l' => $data->p2_indeksplak_ra_el26_l,
'p2_indeksplak_rb_el36_b' => $data->p2_indeksplak_rb_el36_b,
'p2_indeksplak_rb_el34_b' => $data->p2_indeksplak_rb_el34_b,
'p2_indeksplak_rb_el32_b' => $data->p2_indeksplak_rb_el32_b,
'p2_indeksplak_rb_el31_b' => $data->p2_indeksplak_rb_el31_b,
'p2_indeksplak_rb_el41_b' => $data->p2_indeksplak_rb_el41_b,
'p2_indeksplak_rb_el42_b' => $data->p2_indeksplak_rb_el42_b,
'p2_indeksplak_rb_el46_b' => $data->p2_indeksplak_rb_el46_b,
'p2_indeksplak_rb_el36_l' => $data->p2_indeksplak_rb_el36_l,
'p2_indeksplak_rb_el34_l' => $data->p2_indeksplak_rb_el34_l,
'p2_indeksplak_rb_el32_l' => $data->p2_indeksplak_rb_el32_l,
'p2_indeksplak_rb_el31_l' => $data->p2_indeksplak_rb_el31_l,
'p2_indeksplak_rb_el41_l' => $data->p2_indeksplak_rb_el41_l,
'p2_indeksplak_rb_el42_l' => $data->p2_indeksplak_rb_el42_l,
'p2_indeksplak_rb_el46_l' => $data->p2_indeksplak_rb_el46_l,
'p2_bop_ra_el16_b' => $data->p2_bop_ra_el16_b,
'p2_bop_ra_el12_b' => $data->p2_bop_ra_el12_b,
'p2_bop_ra_el11_b' => $data->p2_bop_ra_el11_b,
'p2_bop_ra_el21_b' => $data->p2_bop_ra_el21_b,
'p2_bop_ra_el22_b' => $data->p2_bop_ra_el22_b,
'p2_bop_ra_el24_b' => $data->p2_bop_ra_el24_b,
'p2_bop_ra_el26_b' => $data->p2_bop_ra_el26_b,
'p2_bop_ra_el16_l' => $data->p2_bop_ra_el16_l,
'p2_bop_ra_el12_l' => $data->p2_bop_ra_el12_l,
'p2_bop_ra_el11_l' => $data->p2_bop_ra_el11_l,
'p2_bop_ra_el21_l' => $data->p2_bop_ra_el21_l,
'p2_bop_ra_el22_l' => $data->p2_bop_ra_el22_l,
'p2_bop_ra_el24_l' => $data->p2_bop_ra_el24_l,
'p2_bop_ra_el26_l' => $data->p2_bop_ra_el26_l,
'p2_bop_rb_el36_b' => $data->p2_bop_rb_el36_b,
'p2_bop_rb_el34_b' => $data->p2_bop_rb_el34_b,
'p2_bop_rb_el32_b' => $data->p2_bop_rb_el32_b,
'p2_bop_rb_el31_b' => $data->p2_bop_rb_el31_b,
'p2_bop_rb_el41_b' => $data->p2_bop_rb_el41_b,
'p2_bop_rb_el42_b' => $data->p2_bop_rb_el42_b,
'p2_bop_rb_el46_b' => $data->p2_bop_rb_el46_b,
'p2_bop_rb_el36_l' => $data->p2_bop_rb_el36_l,
'p2_bop_rb_el34_l' => $data->p2_bop_rb_el34_l,
'p2_bop_rb_el32_l' => $data->p2_bop_rb_el32_l,
'p2_bop_rb_el31_l' => $data->p2_bop_rb_el31_l,
'p2_bop_rb_el41_l' => $data->p2_bop_rb_el41_l,
'p2_bop_rb_el42_l' => $data->p2_bop_rb_el42_l,
'p2_bop_rb_el46_l' => $data->p2_bop_rb_el46_l,
'p2_indekskalkulus_ra_el16_b' => $data->p2_indekskalkulus_ra_el16_b,
'p2_indekskalkulus_ra_el26_b' => $data->p2_indekskalkulus_ra_el26_b,
'p2_indekskalkulus_ra_el16_l' => $data->p2_indekskalkulus_ra_el16_l,
'p2_indekskalkulus_ra_el26_l' => $data->p2_indekskalkulus_ra_el26_l,
'p2_indekskalkulus_rb_el36_b' => $data->p2_indekskalkulus_rb_el36_b,
'p2_indekskalkulus_rb_el34_b' => $data->p2_indekskalkulus_rb_el34_b,
'p2_indekskalkulus_rb_el32_b' => $data->p2_indekskalkulus_rb_el32_b,
'p2_indekskalkulus_rb_el31_b' => $data->p2_indekskalkulus_rb_el31_b,
'p2_indekskalkulus_rb_el41_b' => $data->p2_indekskalkulus_rb_el41_b,
'p2_indekskalkulus_rb_el42_b' => $data->p2_indekskalkulus_rb_el42_b,
'p2_indekskalkulus_rb_el46_b' => $data->p2_indekskalkulus_rb_el46_b,
'p2_indekskalkulus_rb_el36_l' => $data->p2_indekskalkulus_rb_el36_l,
'p2_indekskalkulus_rb_el34_l' => $data->p2_indekskalkulus_rb_el34_l,
'p2_indekskalkulus_rb_el32_l' => $data->p2_indekskalkulus_rb_el32_l,
'p2_indekskalkulus_rb_el31_l' => $data->p2_indekskalkulus_rb_el31_l,
'p2_indekskalkulus_rb_el41_l' => $data->p2_indekskalkulus_rb_el41_l,
'p2_indekskalkulus_rb_el42_l' => $data->p2_indekskalkulus_rb_el42_l,
'p2_indekskalkulus_rb_el46_l' => $data->p2_indekskalkulus_rb_el46_l,
'p3_tanggal' => $data->p3_tanggal,
'p3_indeksplak_ra_el16_b' => $data->p3_indeksplak_ra_el16_b,
'p3_indeksplak_ra_el12_b' => $data->p3_indeksplak_ra_el12_b,
'p3_indeksplak_ra_el11_b' => $data->p3_indeksplak_ra_el11_b,
'p3_indeksplak_ra_el21_b' => $data->p3_indeksplak_ra_el21_b,
'p3_indeksplak_ra_el22_b' => $data->p3_indeksplak_ra_el22_b,
'p3_indeksplak_ra_el24_b' => $data->p3_indeksplak_ra_el24_b,
'p3_indeksplak_ra_el26_b' => $data->p3_indeksplak_ra_el26_b,
'p3_indeksplak_ra_el16_l' => $data->p3_indeksplak_ra_el16_l,
'p3_indeksplak_ra_el12_l' => $data->p3_indeksplak_ra_el12_l,
'p3_indeksplak_ra_el11_l' => $data->p3_indeksplak_ra_el11_l,
'p3_indeksplak_ra_el21_l' => $data->p3_indeksplak_ra_el21_l,
'p3_indeksplak_ra_el22_l' => $data->p3_indeksplak_ra_el22_l,
'p3_indeksplak_ra_el24_l' => $data->p3_indeksplak_ra_el24_l,
'p3_indeksplak_ra_el26_l' => $data->p3_indeksplak_ra_el26_l,
'p3_indeksplak_rb_el36_b' => $data->p3_indeksplak_rb_el36_b,
'p3_indeksplak_rb_el34_b' => $data->p3_indeksplak_rb_el34_b,
'p3_indeksplak_rb_el32_b' => $data->p3_indeksplak_rb_el32_b,
'p3_indeksplak_rb_el31_b' => $data->p3_indeksplak_rb_el31_b,
'p3_indeksplak_rb_el41_b' => $data->p3_indeksplak_rb_el41_b,
'p3_indeksplak_rb_el42_b' => $data->p3_indeksplak_rb_el42_b,
'p3_indeksplak_rb_el46_b' => $data->p3_indeksplak_rb_el46_b,
'p3_indeksplak_rb_el36_l' => $data->p3_indeksplak_rb_el36_l,
'p3_indeksplak_rb_el34_l' => $data->p3_indeksplak_rb_el34_l,
'p3_indeksplak_rb_el32_l' => $data->p3_indeksplak_rb_el32_l,
'p3_indeksplak_rb_el31_l' => $data->p3_indeksplak_rb_el31_l,
'p3_indeksplak_rb_el41_l' => $data->p3_indeksplak_rb_el41_l,
'p3_indeksplak_rb_el42_l' => $data->p3_indeksplak_rb_el42_l,
'p3_indeksplak_rb_el46_l' => $data->p3_indeksplak_rb_el46_l,
'p3_bop_ra_el16_b' => $data->p3_bop_ra_el16_b,
'p3_bop_ra_el12_b' => $data->p3_bop_ra_el12_b,
'p3_bop_ra_el11_b' => $data->p3_bop_ra_el11_b,
'p3_bop_ra_el21_b' => $data->p3_bop_ra_el21_b,
'p3_bop_ra_el22_b' => $data->p3_bop_ra_el22_b,
'p3_bop_ra_el24_b' => $data->p3_bop_ra_el24_b,
'p3_bop_ra_el26_b' => $data->p3_bop_ra_el26_b,
'p3_bop_ra_el16_l' => $data->p3_bop_ra_el16_l,
'p3_bop_ra_el12_l' => $data->p3_bop_ra_el12_l,
'p3_bop_ra_el11_l' => $data->p3_bop_ra_el11_l,
'p3_bop_ra_el21_l' => $data->p3_bop_ra_el21_l,
'p3_bop_ra_el22_l' => $data->p3_bop_ra_el22_l,
'p3_bop_ra_el24_l' => $data->p3_bop_ra_el24_l,
'p3_bop_ra_el26_l' => $data->p3_bop_ra_el26_l,
'p3_bop_rb_el36_b' => $data->p3_bop_rb_el36_b,
'p3_bop_rb_el34_b' => $data->p3_bop_rb_el34_b,
'p3_bop_rb_el32_b' => $data->p3_bop_rb_el32_b,
'p3_bop_rb_el31_b' => $data->p3_bop_rb_el31_b,
'p3_bop_rb_el41_b' => $data->p3_bop_rb_el41_b,
'p3_bop_rb_el42_b' => $data->p3_bop_rb_el42_b,
'p3_bop_rb_el46_b' => $data->p3_bop_rb_el46_b,
'p3_bop_rb_el36_l' => $data->p3_bop_rb_el36_l,
'p3_bop_rb_el34_l' => $data->p3_bop_rb_el34_l,
'p3_bop_rb_el32_l' => $data->p3_bop_rb_el32_l,
'p3_bop_rb_el31_l' => $data->p3_bop_rb_el31_l,
'p3_bop_rb_el41_l' => $data->p3_bop_rb_el41_l,
'p3_bop_rb_el42_l' => $data->p3_bop_rb_el42_l,
'p3_bop_rb_el46_l' => $data->p3_bop_rb_el46_l,
'p3_indekskalkulus_ra_el16_b' => $data->p3_indekskalkulus_ra_el16_b,
'p3_indekskalkulus_ra_el26_b' => $data->p3_indekskalkulus_ra_el26_b,
'p3_indekskalkulus_ra_el16_l' => $data->p3_indekskalkulus_ra_el16_l,
'p3_indekskalkulus_ra_el26_l' => $data->p3_indekskalkulus_ra_el26_l,
'p3_indekskalkulus_rb_el36_b' => $data->p3_indekskalkulus_rb_el36_b,
'p3_indekskalkulus_rb_el34_b' => $data->p3_indekskalkulus_rb_el34_b,
'p3_indekskalkulus_rb_el32_b' => $data->p3_indekskalkulus_rb_el32_b,
'p3_indekskalkulus_rb_el31_b' => $data->p3_indekskalkulus_rb_el31_b,
'p3_indekskalkulus_rb_el41_b' => $data->p3_indekskalkulus_rb_el41_b,
'p3_indekskalkulus_rb_el42_b' => $data->p3_indekskalkulus_rb_el42_b,
'p3_indekskalkulus_rb_el46_b' => $data->p3_indekskalkulus_rb_el46_b,
'p3_indekskalkulus_rb_el36_l' => $data->p3_indekskalkulus_rb_el36_l,
'p3_indekskalkulus_rb_el34_l' => $data->p3_indekskalkulus_rb_el34_l,
'p3_indekskalkulus_rb_el32_l' => $data->p3_indekskalkulus_rb_el32_l,
'p3_indekskalkulus_rb_el31_l' => $data->p3_indekskalkulus_rb_el31_l,
'p3_indekskalkulus_rb_el41_l' => $data->p3_indekskalkulus_rb_el41_l,
'p3_indekskalkulus_rb_el42_l' => $data->p3_indekskalkulus_rb_el42_l,
'p3_indekskalkulus_rb_el46_l' => $data->p3_indekskalkulus_rb_el46_l,
// 'foto_klinis_oklusi_arah_kiri' => $data->foto_klinis_oklusi_arah_kiri,
// 'foto_klinis_oklusi_arah_kanan' => $data->foto_klinis_oklusi_arah_kanan,
// 'foto_klinis_oklusi_arah_anterior' => $data->foto_klinis_oklusi_arah_anterior,
// 'foto_klinis_oklusal_rahang_atas' => $data->foto_klinis_oklusal_rahang_atas,
// 'foto_klinis_oklusal_rahang_bawah' => $data->foto_klinis_oklusal_rahang_bawah,
// 'foto_klinis_before' => $data->foto_klinis_before,
// 'foto_klinis_after' => $data->foto_klinis_after,
// 'foto_ronsen_panoramik' => $data->foto_ronsen_panoramik,
'terapi_s' => $data->terapi_s,
'terapi_o' => $data->terapi_o,
'terapi_a' => $data->terapi_a,
'terapi_p' => $data->terapi_p,
'terapi_ohis' => $data->terapi_ohis,
'terapi_bop' => $data->terapi_bop,
'terapi_pm18' => $data->terapi_pm18,
'terapi_pm17' => $data->terapi_pm17,
'terapi_pm16' => $data->terapi_pm16,
'terapi_pm15' => $data->terapi_pm15,
'terapi_pm14' => $data->terapi_pm14,
'terapi_pm13' => $data->terapi_pm13,
'terapi_pm12' => $data->terapi_pm12,
'terapi_pm11' => $data->terapi_pm11,
'terapi_pm21' => $data->terapi_pm21,
'terapi_pm22' => $data->terapi_pm22,
'terapi_pm23' => $data->terapi_pm23,
'terapi_pm24' => $data->terapi_pm24,
'terapi_pm25' => $data->terapi_pm25,
'terapi_pm26' => $data->terapi_pm26,
'terapi_pm27' => $data->terapi_pm27,
'terapi_pm28' => $data->terapi_pm28,
'terapi_pm38' => $data->terapi_pm38,
'terapi_pm37' => $data->terapi_pm37,
'terapi_pm36' => $data->terapi_pm36,
'terapi_pm35' => $data->terapi_pm35,
'terapi_pm34' => $data->terapi_pm34,
'terapi_pm33' => $data->terapi_pm33,
'terapi_pm32' => $data->terapi_pm32,
'terapi_pm31' => $data->terapi_pm31,
'terapi_pm41' => $data->terapi_pm41,
'terapi_pm42' => $data->terapi_pm42,
'terapi_pm43' => $data->terapi_pm43,
'terapi_pm44' => $data->terapi_pm44,
'terapi_pm45' => $data->terapi_pm45,
'terapi_pm46' => $data->terapi_pm46,
'terapi_pm47' => $data->terapi_pm47,
'terapi_pm48' => $data->terapi_pm48,
'terapi_pb18' => $data->terapi_pb18,
'terapi_pb17' => $data->terapi_pb17,
'terapi_pb16' => $data->terapi_pb16,
'terapi_pb15' => $data->terapi_pb15,
'terapi_pb14' => $data->terapi_pb14,
'terapi_pb13' => $data->terapi_pb13,
'terapi_pb12' => $data->terapi_pb12,
'terapi_pb11' => $data->terapi_pb11,
'terapi_pb21' => $data->terapi_pb21,
'terapi_pb22' => $data->terapi_pb22,
'terapi_pb23' => $data->terapi_pb23,
'terapi_pb24' => $data->terapi_pb24,
'terapi_pb25' => $data->terapi_pb25,
'terapi_pb26' => $data->terapi_pb26,
'terapi_pb27' => $data->terapi_pb27,
'terapi_pb28' => $data->terapi_pb28,
'terapi_pb38' => $data->terapi_pb38,
'terapi_pb37' => $data->terapi_pb37,
'terapi_pb36' => $data->terapi_pb36,
'terapi_pb35' => $data->terapi_pb35,
'terapi_pb34' => $data->terapi_pb34,
'terapi_pb33' => $data->terapi_pb33,
'terapi_pb32' => $data->terapi_pb32,
'terapi_pb31' => $data->terapi_pb31,
'terapi_pb41' => $data->terapi_pb41,
'terapi_pb42' => $data->terapi_pb42,
'terapi_pb43' => $data->terapi_pb43,
'terapi_pb44' => $data->terapi_pb44,
'terapi_pb45' => $data->terapi_pb45,
'terapi_pb46' => $data->terapi_pb46,
'terapi_pb47' => $data->terapi_pb47,
'terapi_pb48' => $data->terapi_pb48,
'terapi_pd18' => $data->terapi_pd18,
'terapi_pd17' => $data->terapi_pd17,
'terapi_pd16' => $data->terapi_pd16,
'terapi_pd15' => $data->terapi_pd15,
'terapi_pd14' => $data->terapi_pd14,
'terapi_pd13' => $data->terapi_pd13,
'terapi_pd12' => $data->terapi_pd12,
'terapi_pd11' => $data->terapi_pd11,
'terapi_pd21' => $data->terapi_pd21,
'terapi_pd22' => $data->terapi_pd22,
'terapi_pd23' => $data->terapi_pd23,
'terapi_pd24' => $data->terapi_pd24,
'terapi_pd25' => $data->terapi_pd25,
'terapi_pd26' => $data->terapi_pd26,
'terapi_pd27' => $data->terapi_pd27,
'terapi_pd28' => $data->terapi_pd28,
'terapi_pd38' => $data->terapi_pd38,
'terapi_pd37' => $data->terapi_pd37,
'terapi_pd36' => $data->terapi_pd36,
'terapi_pd35' => $data->terapi_pd35,
'terapi_pd34' => $data->terapi_pd34,
'terapi_pd33' => $data->terapi_pd33,
'terapi_pd32' => $data->terapi_pd32,
'terapi_pd31' => $data->terapi_pd31,
'terapi_pd41' => $data->terapi_pd41,
'terapi_pd42' => $data->terapi_pd42,
'terapi_pd43' => $data->terapi_pd43,
'terapi_pd44' => $data->terapi_pd44,
'terapi_pd45' => $data->terapi_pd45,
'terapi_pd46' => $data->terapi_pd46,
'terapi_pd47' => $data->terapi_pd47,
'terapi_pd48' => $data->terapi_pd48,
'terapi_pl18' => $data->terapi_pl18,
'terapi_pl17' => $data->terapi_pl17,
'terapi_pl16' => $data->terapi_pl16,
'terapi_pl15' => $data->terapi_pl15,
'terapi_pl14' => $data->terapi_pl14,
'terapi_pl13' => $data->terapi_pl13,
'terapi_pl12' => $data->terapi_pl12,
'terapi_pl11' => $data->terapi_pl11,
'terapi_pl21' => $data->terapi_pl21,
'terapi_pl22' => $data->terapi_pl22,
'terapi_pl23' => $data->terapi_pl23,
'terapi_pl24' => $data->terapi_pl24,
'terapi_pl25' => $data->terapi_pl25,
'terapi_pl26' => $data->terapi_pl26,
'terapi_pl27' => $data->terapi_pl27,
'terapi_pl28' => $data->terapi_pl28,
'terapi_pl38' => $data->terapi_pl38,
'terapi_pl37' => $data->terapi_pl37,
'terapi_pl36' => $data->terapi_pl36,
'terapi_pl35' => $data->terapi_pl35,
'terapi_pl34' => $data->terapi_pl34,
'terapi_pl33' => $data->terapi_pl33,
'terapi_pl32' => $data->terapi_pl32,
'terapi_pl31' => $data->terapi_pl31,
'terapi_pl41' => $data->terapi_pl41,
'terapi_pl42' => $data->terapi_pl42,
'terapi_pl43' => $data->terapi_pl43,
'terapi_pl44' => $data->terapi_pl44,
'terapi_pl45' => $data->terapi_pl45,
'terapi_pl46' => $data->terapi_pl46,
'terapi_pl47' => $data->terapi_pl47,
'terapi_pl48' => $data->terapi_pl48,
'created_at' => $data->created_at,
'updated_at' => $data->updated_at,
        ]);
        return $updates;
    }
    public function foto_klinis_oklusi_arah_kiri($data,$awsurl)
    { 
        $updates = emrperiodontie::where('id', $data->id)->update([ 
            'foto_klinis_oklusi_arah_kiri' => $awsurl 
        ]);
        return $updates;
    }
    public function foto_klinis_oklusi_arah_kanan($data,$awsurl)
    { 
        $updates = emrperiodontie::where('id', $data->id)->update([ 
            'foto_klinis_oklusi_arah_kanan' => $awsurl 
        ]);
        return $updates;
    }
    public function foto_klinis_oklusi_arah_anterior($data,$awsurl)
    { 
        $updates = emrperiodontie::where('id', $data->id)->update([ 
            'foto_klinis_oklusi_arah_anterior' => $awsurl 
        ]);
        return $updates;
    }
    public function foto_klinis_oklusal_rahang_atas($data,$awsurl)
    { 
        $updates = emrperiodontie::where('id', $data->id)->update([ 
            'foto_klinis_oklusal_rahang_atas' => $awsurl 
        ]);
        return $updates;
    }
    public function foto_klinis_oklusal_rahang_bawah($data,$awsurl)
    { 
        $updates = emrperiodontie::where('id', $data->id)->update([ 
            'foto_klinis_oklusal_rahang_bawah' => $awsurl 
        ]);
        return $updates;
    }

    public function  foto_klinis_before($data,$awsurl)
    { 
        $updates = emrperiodontie::where('id', $data->id)->update([ 
            'foto_klinis_before' => $awsurl 
        ]);
        return $updates;
    }
    public function foto_klinis_after($data,$awsurl)
    { 
        $updates = emrperiodontie::where('id', $data->id)->update([ 
            'foto_klinis_after' => $awsurl 
        ]);
        return $updates;
    }
    public function foto_ronsen_panoramik($data,$awsurl)
    { 
        $updates = emrperiodontie::where('id', $data->id)->update([ 
            'foto_ronsen_panoramik' => $awsurl 
        ]);
        return $updates;
    }

    //soap
    public function createsoap($data)
    { 
        return  emrperiodontie_soap::insert($data);
    }
    public function updatesoap($data)
    { 
        $updates = emrperiodontie_soap::where('id', $data['id'])->update([ 
            'terapi_s' => $data['terapi_s'],
            'terapi_o' => $data['terapi_o'], 
            'terapi_a' => $data['terapi_a'],         
            'terapi_p' => $data['terapi_p'], 
        ]);
        return $updates;
    }
    public function verifydpk($data)
    { 
        $updates = emrperiodontie_soap::where('id', $data['id'])->update([ 
            'user_verify' => $data['user_verify'],
            'user_verify_name' => $data['user_verify_name'], 
            'date_verify' => $data['date_verify'],    
        ]);
        return $updates;
    }
    public function deletesoap($data)
    { 
        $updates = emrperiodontie_soap::where('id', $data['id'])->update([ 
            'active' => $data['active'], 
        ]);
        return $updates;
  
    }
    public function showbyidsoap($data)
    { 
        return emrperiodontie_soap::where('id',$data->id)->where('active','1')->get();
    }
    public function showallsoap($data)
    { 
        return emrperiodontie_soap::where('idemr',$data->idemr)->where('active','1')->orderBy('id', 'DESC')->latest()->paginate(10);
    }
}
